=== carolbgmm/F1Desktop/xml/circuito.dtd
<!ELEMENT circuito(nombre, longitud, anchura, fecha, hora, vueltas, localidad, pais, referencias, fotos, videos,coord,tramos)>
<!ELEMENT nombre(#PCDATA)>
<!ELEMENT longitud(#PCDATA)>
<!ELEMENT anchura(#PCDATA)>
<!ELEMENT fecha(#PCDATA)>
<!ELEMENT hora(#PCDATA)>
<!ELEMENT vueltas(#PCDATA)>
<!ELEMENT localidad(#PCDATA)>
<!ELEMENT pais(#PCDATA)>
<!ELEMENT referencias(referencia+)>
<!ELEMENT referencia(#PCDATA)>
<!ELEMENT fotos(foto)>
<!ELEMENT foto(#PCDATA)>
<!ELEMENT videos(video*)>
<!ELEMENT video(#PCDATA)>
<!ELEMENT coord(#PCDATA)>
<!ELEMENT tramos(tramo+)>
<!ELEMENT tramo(#PCDATA)>
<!ELEMENT distancia(#PCDATA)>
<!ELEMENT sector(#PCDATA)>
<!ATTLIST longitud unidad CDATA #REQUIRED valor CDATA #REQUIRED>
<!ATTLIST anchura unidad CDATA #REQUIRED valor CDATA #REQUIRED>
<!ATTLIST coord latitud CDATA #REQUIRED longitud CDATA #REQUIRED altitud CDATA #REQUIRED>
<!ATTLIST distancia unidad CDATA #REQUIRED valor CDATA #REQUIRED>

=== carolbgmm/F1Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
    <nombre>"Barcelona-Catalunya"</nombre>
    <longitud unidad="m" valor="4655"></longitud>
    <anchura unidad="m" valor="12"></anchura>
    <fecha>"23/06/2024"</fecha>
    <hora>"13:00"</hora>
    <vueltas>"66"</vueltas>
    <localidad>"Barcelona"</localidad>
    <pais>"Espa√±a"</pais>
    <referencias>
        <referencia>"https://www.formula1.com/en/information/spain-circuit-de-barcelona-catalunya-barcelona.6F5mWJGRuYkQ1XPX48pl8"</referencia>
        <referencia>"https://soymotero.net/competicion/el-circuito-de-cataluna-al-detalle/"</referencia>
        <referencia>"https://veloviewer.com/segment/4064048/Circuit+de+Catalunya+-+F1+Circuit+Full+Lap"</referencia>
    </referencias>
    <fotos>
        <foto>"Circuit_de_Catalunya.svg"</foto>
        <foto>"FotoAerea_2021.jpg"</foto>
        <foto>"mapa-barcenola-2024.webp"</foto>
    </fotos>
    <videos>
        <video>"barcenola_2016.mp4"</video>
    </videos>
    <coord latitud="41.570582" longitud="2.259647" altitud="130"></coord>
    <tramos>
        <tramo distancia="0" latitud="41.570019" longitud="2.261233" altitud="130" nsector="01"></tramo>
        <tramo distancia="250" latitud="41.567756" longitud="2.259325" altitud="133" nsector="01"></tramo>
        <tramo distancia="250" latitud="41.566496" longitud="2.258293" altitud="130" nsector="01"></tramo>
        <tramo distancia="250" latitud="41.564726" longitud="2.256074" altitud="126" nsector="01"></tramo>
        <tramo distancia="140" latitud="41.564749" longitud="2.256035" altitud="124" nsector="01"></tramo>
        <tramo distancia="110" latitud="41.564883" longitud="2.255374" altitud="127" nsector="01"></tramo> 
        <!-- 1 km-->
        <tramo distancia="250" latitud="41.565119" longitud="2.252126" altitud="136" nsector="01"></tramo>
        <tramo distancia="250" latitud="41.566802" longitud="2.252785" altitud="139" nsector="01"></tramo>
        <tramo distancia="250" latitud="41.568319" longitud="2.254963" altitud="142" nsector="02"></tramo>
        <tramo distancia="100" latitud="41.567315" longitud="2.255270" altitud="144" nsector="02"></tramo>
        <tramo distancia="150" latitud="41.566446" longitud="2.254595" altitud="142" nsector="02"></tramo>
        <!-- 2 km-->
        <tramo distancia="250" latitud="41.565833" longitud="2.256120" altitud="133" nsector="02"></tramo>
        <tramo distancia="250" latitud="41.567377" longitud="2.257804" altitud="126" nsector="02"></tramo>
        <tramo distancia="250" latitud="41.568813" longitud="2.256567" altitud="138" nsector="02"></tramo>
        <tramo distancia="250" latitud="41.570771" longitud="2.256893" altitud="146" nsector="02"></tramo>
        <!-- 3 km-->
        <tramo distancia="250" latitud="41.571946" longitud="2.259822" altitud="143" nsector="02"></tramo>
        <tramo distancia="200" latitud="41.572968" longitud="2.261954" altitud="140" nsector="03"></tramo>
        <tramo distancia="50" latitud="41.573324" longitud="2.261530" altitud="141" nsector="03"></tramo>
        <tramo distancia="250" latitud="41.573883" longitud="2.259323" altitud="149" nsector="03"></tramo>
        <tramo distancia="250" latitud="41.574632" longitud="2.261613" altitud="145" nsector="03"></tramo>
        <!-- 4 km-->
        <tramo distancia="250" latitud="41.573667" longitud="2.263470" altitud="134" nsector="03"></tramo>
        <tramo distancia="250" latitud="41.571847" longitud="2.262729" altitud="130" nsector="03"></tramo>
    </tramos>
</circuito>
