=== carolbgmm/F1Desktop/xml/otros/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" 
		   targetNamespace="http://www.uniovi.es" 
		   elementFormDefault="qualified" 
		   xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="longitud" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="anchura" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="fecha" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="hora-inicio" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="numero-vueltas" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="localidad" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="pais" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="bibliografia" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="galeria-fotos" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="galeria-videos" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="centro-pista" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="tramos" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!--Expresion del nombre-->
	<xs:element name="name" type="xs:string" />
	
	<!--Expresion de la longuitud-->
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="medidaPositiva">
					<xs:attribute name="mesure" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<!--Expresion de la anchura-->
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="medidaPositiva">
					<xs:attribute name="mesure" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<!--Expresion tipo medidaPositiva (m>=0)-->
	<xs:simpleType name="medidaPositiva">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>

	<!--Expresion de la fecha de la carrera-->
	<xs:element name="fecha" type="xs:date" />

	<!--Expresion de la hora de inicio-->
	<xs:element name="hora-inicio" type="xs:time" />

	<!--Expresion del numero de vueltas-->
	<xs:element name="numero-vueltas" type="xs:unsignedInt" />
	
	<!--Expresion de la localidad del circuito-->
	<xs:element name="localidad" type="xs:string" />

	<!--Expresion del pais-->
	<xs:element name="pais" type="xs:string" />
	
	<!--Expresion de la bibliografia (enlacces min:3)-->
	<xs:element name="bibliografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="enlace"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!--Expresion del enlace-->
	<xs:element name="enlace" type="xs:anyURI" />
	
	<!--Expresion de la galeria de fotos (1>imagen<5)-->
	<xs:element name="galeria-fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="imagen" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!--Expresion de la galeria de videos (0>video<3)-->
	<xs:element name="galeria-videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!--Expresion de las imagenes-->
	<xs:element name="imagen" type="xs:string" />

	<!--Expresion de los videos-->
	<xs:element name="video" type="xs:string" />

	<!--Expresion del centro de la pista-->
	<xs:element name="centro-pista">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenada" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!--Expresion de una coordenada-->
	<xs:element name="coordenada">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud-coord" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!--Exprexion del tipo medidaLonguitud (-180.00=<long=<180.00)-->
	<xs:simpleType name="medidaLonguitud">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="-180.00"/>
			<xs:maxInclusive value="180.00"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!--Exprexion del tipo medidaLatitud (-90.00=<lati=<90.00)-->
	<xs:simpleType name="medidaLatitud">
		<xs:restriction base="xs:double">
			<xs:minInclusive value="-90.00"/>
			<xs:maxInclusive value="90.00"/>
		</xs:restriction>
	</xs:simpleType>

	<!--Expresion de la longuitud de una coordenada-->
	<xs:element name="longitud-coord">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="medidaLonguitud">
					<xs:attribute name="mesure" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!--Expresion de la latitud de una coordenada-->
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="medidaLatitud">
					<xs:attribute name="mesure" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!--Expresion de la altitud de una coordenada-->
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="medidaPositiva">
					<xs:attribute name="mesure" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!--Expresion de los tramos del circuito-->
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!--Expresion de un tramo-->
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenada" />
				<xs:element ref="distancia" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!--Expresion de la distancia-->
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="medidaPositiva">
					<xs:attribute name="mesure" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!--Expresion del sector-->
	<xs:element name="sector">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:enumeration value="1"/>
				<xs:enumeration value="2"/>
				<xs:enumeration value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== carolbgmm/F1Desktop/xml/otros/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- (288339modulo24) + 1 = 4. Circuto Suzuka-->

    <circuito xmlns="http://www.uniovi.es"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.uniovi.es circuito.xsd"> 
        <name>Circuito de Suzuka</name>
        <longitud mesure="km">5807</longitud>
        <!-- Buscar ancho de pista correcto-->
        <anchura mesure="m">14</anchura>
        <fecha>2024-07-04</fecha>
        <hora-inicio>07:00:00</hora-inicio>
        <numero-vueltas>53</numero-vueltas>
        <localidad>Suzuka</localidad>
        <pais>Jap√≥n</pais>
        <bibliografia>
            <enlace>https://www.dazn.com/es-ES/news/motor/circuito-de-suzuka-donde-esta-como-es-caracteristicas-como-llegar-y-fotos-del-escenario-del-gp-de-japon-del-mundial-de-f1/vu94vtds0aox1er5hf8nnveym</enlace>
            <enlace>https://www.statsf1.com/es/circuit-suzuka.aspx</enlace>
            <enlace>https://es.wikipedia.org/wiki/Circuito_de_Suzuka</enlace>
        </bibliografia>
        <galeria-fotos>
            <imagen>linea-meta.jpg</imagen>
            <imagen>paso-a-nivel.jpg</imagen>
            <imagen>vista-aerea.jpg</imagen>
        </galeria-fotos>
        <galeria-videos>
            <video>suzuka-race-guide.mp4</video>
        </galeria-videos>
        <centro-pista>
            <coordenada>
                <longitud-coord mesure="grados">136.5388889</longitud-coord>
                <latitud mesure="grados">34.8447222</latitud>
                <altitud mesure="m">38</altitud>
            </coordenada>
        </centro-pista>
        <tramos>
            <!-- SECTOR 1-->
            <!-- TRAMO 1.1-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5433346</longitud-coord>
                    <latitud mesure="grados">34.8402305</latitud>
                    <altitud mesure="m">20.51</altitud>
                </coordenada>
                <distancia mesure="m">643.15</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMMO 1.2-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5434260</longitud-coord>
                    <latitud mesure="grados">34.8398812</latitud>
                    <altitud mesure="m">19.34</altitud>
                </coordenada>
                <distancia mesure="m">39.66</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.3-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5431686</longitud-coord>
                    <latitud mesure="grados">34.8391703</latitud>
                    <altitud mesure="m">18.49</altitud>
                </coordenada>
                <distancia mesure="m">82.34</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.4-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5426565</longitud-coord>
                    <latitud mesure="grados">34.8389238</latitud>
                    <altitud mesure="m">19.25</altitud>
                </coordenada>
                <distancia mesure="m">54.19</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.5-->
              <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5421636</longitud-coord>
                    <latitud mesure="grados">34.8390760</latitud>
                    <altitud mesure="m">21.14</altitud>
                </coordenada>
                <distancia mesure="m">48.2</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.6-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5410236</longitud-coord>
                    <latitud mesure="grados">34.8405141</latitud>
                    <altitud mesure="m">24.01</altitud>
                </coordenada>
                <distancia mesure="m">190.6</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.7-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5406053</longitud-coord>
                    <latitud mesure="grados">34.8406858</latitud>
                    <altitud mesure="m">25.22</altitud>
                </coordenada>
                <distancia mesure="m">42.74</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.8-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5400207</longitud-coord>
                    <latitud mesure="grados">34.8407114</latitud>
                    <altitud mesure="m">26.8</altitud>
                </coordenada>
                <distancia mesure="m">53.36</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.9-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5397198</longitud-coord>
                    <latitud mesure="grados">34.8408130</latitud>
                    <altitud mesure="m">28.23</altitud>
                </coordenada>
                <distancia mesure="m">29.75</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.10-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5394586</longitud-coord>
                    <latitud mesure="grados">34.8410753</latitud>
                    <altitud mesure="m">29.88</altitud>
                </coordenada>
                <distancia mesure="m">37.62</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.11-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5391515</longitud-coord>
                    <latitud mesure="grados">34.8419306</latitud>
                    <altitud mesure="m">34.34</altitud>
                </coordenada>
                <distancia mesure="m">99.99</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.12-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5388884</longitud-coord>
                    <latitud mesure="grados">34.8421749</latitud>
                    <altitud mesure="m">36.03</altitud>
                </coordenada>
                <distancia mesure="m">36.33</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.13-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5384014</longitud-coord>
                    <latitud mesure="grados">34.8422871</latitud>
                    <altitud mesure="m">38.24</altitud>
                </coordenada>
                <distancia mesure="m">46.26</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.14-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5376792</longitud-coord>
                    <latitud mesure="grados">34.8423187</latitud>
                    <altitud mesure="m">40.27</altitud>
                </coordenada>
                <distancia mesure="m">66.17</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.15-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5372065</longitud-coord>
                    <latitud mesure="grados">34.8425796</latitud>
                    <altitud mesure="m">40.29</altitud>
                </coordenada>
                <distancia mesure="m">52.03</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.16-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5370005</longitud-coord>
                    <latitud mesure="grados">34.8429990</latitud>
                    <altitud mesure="m">39.27</altitud>
                </coordenada>
                <distancia mesure="m">50.21</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.17-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5373476</longitud-coord>
                    <latitud mesure="grados">34.8439126</latitud>
                    <altitud mesure="m">39.38</altitud>
                </coordenada>
                <distancia mesure="m">106.22</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.18-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5373355</longitud-coord>
                    <latitud mesure="grados">34.8442986</latitud>
                    <altitud mesure="m">42.46</altitud>
                </coordenada>
                <distancia mesure="m">42.86</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.19-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5370756</longitud-coord>
                    <latitud mesure="grados">34.8446215</latitud>
                    <altitud mesure="m">45.69</altitud>
                </coordenada>
                <distancia mesure="m">43.11</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.20-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136.5360662</longitud-coord>
                    <latitud mesure="grados">34.8450138</latitud>
