=== carolbgmm/F1Desktop/xml/otros/xml/circuito.dtd
<!ELEMENT circuito (name, longitud, 
                    anchura, fecha, 
                    hora-inicio,
                    numero-vueltas,
                    localidad, pais,
                    bibliografia, 
                    galeria-fotos,
                    galeria-videos,
                    centro-pista,
                    tramos)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT anchura (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora-inicio (#PCDATA)>
<!ELEMENT numero-vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
    <!-- Expresion de bibliografia-->
<!ELEMENT bibliografia (enlace+)>
<!ELEMENT enlace (#PCDATA)>
    <!-- Expresion de galeria-->
<!ELEMENT galeria-fotos (imagen+)>
<!ELEMENT galeria-videos (video*)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT video (#PCDATA)>
    <!-- Expresion centro de la pista-->
<!ELEMENT centro-pista (coordenada)>
    <!-- expresion de coordenada-->
<!ELEMENT coordenada (longitud-coord, latitud, altitud)>
<!ELEMENT longitud-coord (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
    <!-- expresion de tramos-->
<!ELEMENT tramos (tramo+)>
    <!-- Expresion de tramo-->
<!ELEMENT tramo (coordenada, distancia, sector)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT sector (#PCDATA)>


<!ATTLIST longitud
    mesure CDATA #REQUIRED>
<!ATTLIST anchura
    mesure CDATA #REQUIRED>
<!ATTLIST longitud-coord
    mesure CDATA #REQUIRED>
<!ATTLIST latitud
    mesure CDATA #REQUIRED>
<!ATTLIST altitud
    mesure CDATA #REQUIRED>
<!ATTLIST distancia 
    mesure CDATA #REQUIRED>

=== carolbgmm/F1Desktop/xml/otros/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<!-- (288339modulo24) + 1 = 4. Circuto Suzuka-->


    <circuito> 
        <name>Circuito de Suzuka</name>
        <longitud mesure="km">5807</longitud>
        <!-- Buscar ancho de pista correcto-->
        <anchura mesure="m">14</anchura>
        <fecha>07/04/2024</fecha>
        <hora-inicio>07:00</hora-inicio>
        <numero-vueltas>53</numero-vueltas>
        <localidad>Suzuka</localidad>
        <pais>Jap√≥n</pais>
        <bibliografia>
            <enlace>"https://www.dazn.com/es-ES/news/motor/circuito-de-suzuka-donde-esta-como-es-caracteristicas-como-llegar-y-fotos-del-escenario-del-gp-de-japon-del-mundial-de-f1/vu94vtds0aox1er5hf8nnveym"</enlace>
            <enlace>"https://www.statsf1.com/es/circuit-suzuka.aspx"</enlace>
            <enlace>"https://es.wikipedia.org/wiki/Circuito_de_Suzuka"</enlace>
        </bibliografia>
        <galeria-fotos>
            <imagen>"linea-meta.jpg"</imagen>
            <imagen>"paso-a-nivel.jpg"</imagen>
            <imagen>"vista-aerea.jpg"</imagen>
        </galeria-fotos>
        <galeria-videos>
            <video>"suzuka-race-guide.mp4"</video>
        </galeria-videos>
        <centro-pista>
            <coordenada>
                <longitud-coord mesure="grados">136,5388889</longitud-coord>
                <latitud mesure="grados">34,8447222</latitud>
                <altitud mesure="m">38</altitud>
            </coordenada>
        </centro-pista>
        <tramos>
            <!-- SECTOR 1-->
            <!-- TRAMO 1.1-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5433346</longitud-coord>
                    <latitud mesure="grados">34,8402305</latitud>
                    <altitud mesure="m">20,51</altitud>
                </coordenada>
                <distancia mesure="m">643,15</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMMO 1.2-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5434260</longitud-coord>
                    <latitud mesure="grados">34,8398812</latitud>
                    <altitud mesure="m">19,34</altitud>
                </coordenada>
                <distancia mesure="m">39,66</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.3-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5431686</longitud-coord>
                    <latitud mesure="grados">34,8391703</latitud>
                    <altitud mesure="m">18,49</altitud>
                </coordenada>
                <distancia mesure="m">82,34</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.4-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5426565</longitud-coord>
                    <latitud mesure="grados">34,8389238</latitud>
                    <altitud mesure="m">19,25</altitud>
                </coordenada>
                <distancia mesure="m">54,19</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.5-->
              <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5421636</longitud-coord>
                    <latitud mesure="grados">34,8390760</latitud>
                    <altitud mesure="m">21,14</altitud>
                </coordenada>
                <distancia mesure="m">48,2</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.6-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5410236</longitud-coord>
                    <latitud mesure="grados">34,8405141</latitud>
                    <altitud mesure="m">24,01</altitud>
                </coordenada>
                <distancia mesure="m">190,6</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.7-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5406053</longitud-coord>
                    <latitud mesure="grados">34,8406858</latitud>
                    <altitud mesure="m">25,22</altitud>
                </coordenada>
                <distancia mesure="m">42,74</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.8-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5400207</longitud-coord>
                    <latitud mesure="grados">34,8407114</latitud>
                    <altitud mesure="m">26,8</altitud>
                </coordenada>
                <distancia mesure="m">53,36</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.9-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5397198</longitud-coord>
                    <latitud mesure="grados">34,8408130</latitud>
                    <altitud mesure="m">28,23</altitud>
                </coordenada>
                <distancia mesure="m">29,75</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.10-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5394586</longitud-coord>
                    <latitud mesure="grados">34,8410753</latitud>
                    <altitud mesure="m">29,88</altitud>
                </coordenada>
                <distancia mesure="m">37,62</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.11-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5391515</longitud-coord>
                    <latitud mesure="grados">34,8419306</latitud>
                    <altitud mesure="m">34,34</altitud>
                </coordenada>
                <distancia mesure="m">99,99</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.12-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5388884</longitud-coord>
                    <latitud mesure="grados">34,8421749</latitud>
                    <altitud mesure="m">36,03</altitud>
                </coordenada>
                <distancia mesure="m">36,33</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.13-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5384014</longitud-coord>
                    <latitud mesure="grados">34,8422871</latitud>
                    <altitud mesure="m">38,24</altitud>
                </coordenada>
                <distancia mesure="m">46,26</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.14-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5376792</longitud-coord>
                    <latitud mesure="grados">34,8423187</latitud>
                    <altitud mesure="m">40,27</altitud>
                </coordenada>
                <distancia mesure="m">66,17</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.15-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5372065</longitud-coord>
                    <latitud mesure="grados">34,8425796</latitud>
                    <altitud mesure="m">40,29</altitud>
                </coordenada>
                <distancia mesure="m">52,03</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.16-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5370005</longitud-coord>
                    <latitud mesure="grados">34,8429990</latitud>
                    <altitud mesure="m">39,27</altitud>
                </coordenada>
                <distancia mesure="m">50,21</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.17-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5373476</longitud-coord>
                    <latitud mesure="grados">34,8439126</latitud>
                    <altitud mesure="m">39,38</altitud>
                </coordenada>
                <distancia mesure="m">106,22</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.18-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5373355</longitud-coord>
                    <latitud mesure="grados">34,8442986</latitud>
                    <altitud mesure="m">42,46</altitud>
                </coordenada>
                <distancia mesure="m">42,86</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.19-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5370756</longitud-coord>
                    <latitud mesure="grados">34,8446215</latitud>
                    <altitud mesure="m">45,69</altitud>
                </coordenada>
                <distancia mesure="m">43,11</distancia>
                <sector>1</sector>
            </tramo>
            <!-- TRAMO 1.20-->
            <tramo>
                <coordenada>
                    <longitud-coord mesure="grados">136,5360662</longitud-coord>
                    <latitud mesure="grados">34,8450138</latitud>
                    <altitud mesure="m">51,65</altitud>
                </coordenada>
